// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/moqi.proto

package moqipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method int32

const (
	Method_METHOD_UNSPECIFIED                Method = 0
	Method_METHOD_INIT                       Method = 1
	Method_METHOD_CLOSE                      Method = 2
	Method_METHOD_ON_ACTIVATE                Method = 3
	Method_METHOD_ON_DEACTIVATE              Method = 4
	Method_METHOD_FILTER_KEY_DOWN            Method = 5
	Method_METHOD_ON_KEY_DOWN                Method = 6
	Method_METHOD_FILTER_KEY_UP              Method = 7
	Method_METHOD_ON_KEY_UP                  Method = 8
	Method_METHOD_ON_PRESERVED_KEY           Method = 9
	Method_METHOD_ON_COMMAND                 Method = 10
	Method_METHOD_ON_MENU                    Method = 11
	Method_METHOD_ON_COMPARTMENT_CHANGED     Method = 12
	Method_METHOD_ON_KEYBOARD_STATUS_CHANGED Method = 13
	Method_METHOD_ON_COMPOSITION_TERMINATED  Method = 14
	Method_METHOD_ON_LANG_PROFILE_ACTIVATED  Method = 15
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0:  "METHOD_UNSPECIFIED",
		1:  "METHOD_INIT",
		2:  "METHOD_CLOSE",
		3:  "METHOD_ON_ACTIVATE",
		4:  "METHOD_ON_DEACTIVATE",
		5:  "METHOD_FILTER_KEY_DOWN",
		6:  "METHOD_ON_KEY_DOWN",
		7:  "METHOD_FILTER_KEY_UP",
		8:  "METHOD_ON_KEY_UP",
		9:  "METHOD_ON_PRESERVED_KEY",
		10: "METHOD_ON_COMMAND",
		11: "METHOD_ON_MENU",
		12: "METHOD_ON_COMPARTMENT_CHANGED",
		13: "METHOD_ON_KEYBOARD_STATUS_CHANGED",
		14: "METHOD_ON_COMPOSITION_TERMINATED",
		15: "METHOD_ON_LANG_PROFILE_ACTIVATED",
	}
	Method_value = map[string]int32{
		"METHOD_UNSPECIFIED":                0,
		"METHOD_INIT":                       1,
		"METHOD_CLOSE":                      2,
		"METHOD_ON_ACTIVATE":                3,
		"METHOD_ON_DEACTIVATE":              4,
		"METHOD_FILTER_KEY_DOWN":            5,
		"METHOD_ON_KEY_DOWN":                6,
		"METHOD_FILTER_KEY_UP":              7,
		"METHOD_ON_KEY_UP":                  8,
		"METHOD_ON_PRESERVED_KEY":           9,
		"METHOD_ON_COMMAND":                 10,
		"METHOD_ON_MENU":                    11,
		"METHOD_ON_COMPARTMENT_CHANGED":     12,
		"METHOD_ON_KEYBOARD_STATUS_CHANGED": 13,
		"METHOD_ON_COMPOSITION_TERMINATED":  14,
		"METHOD_ON_LANG_PROFILE_ACTIVATED":  15,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_moqi_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_proto_moqi_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{0}
}

type ButtonType int32

const (
	ButtonType_BUTTON_TYPE_UNSPECIFIED ButtonType = 0
	ButtonType_BUTTON_TYPE_BUTTON      ButtonType = 1
	ButtonType_BUTTON_TYPE_TOGGLE      ButtonType = 2
	ButtonType_BUTTON_TYPE_MENU        ButtonType = 3
)

// Enum value maps for ButtonType.
var (
	ButtonType_name = map[int32]string{
		0: "BUTTON_TYPE_UNSPECIFIED",
		1: "BUTTON_TYPE_BUTTON",
		2: "BUTTON_TYPE_TOGGLE",
		3: "BUTTON_TYPE_MENU",
	}
	ButtonType_value = map[string]int32{
		"BUTTON_TYPE_UNSPECIFIED": 0,
		"BUTTON_TYPE_BUTTON":      1,
		"BUTTON_TYPE_TOGGLE":      2,
		"BUTTON_TYPE_MENU":        3,
	}
)

func (x ButtonType) Enum() *ButtonType {
	p := new(ButtonType)
	*p = x
	return p
}

func (x ButtonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_moqi_proto_enumTypes[1].Descriptor()
}

func (ButtonType) Type() protoreflect.EnumType {
	return &file_proto_moqi_proto_enumTypes[1]
}

func (x ButtonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonType.Descriptor instead.
func (ButtonType) EnumDescriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{1}
}

type TrayNotificationIcon int32

const (
	TrayNotificationIcon_TRAY_NOTIFICATION_ICON_UNSPECIFIED TrayNotificationIcon = 0
	TrayNotificationIcon_TRAY_NOTIFICATION_ICON_INFO        TrayNotificationIcon = 1
	TrayNotificationIcon_TRAY_NOTIFICATION_ICON_WARNING     TrayNotificationIcon = 2
	TrayNotificationIcon_TRAY_NOTIFICATION_ICON_ERROR       TrayNotificationIcon = 3
)

// Enum value maps for TrayNotificationIcon.
var (
	TrayNotificationIcon_name = map[int32]string{
		0: "TRAY_NOTIFICATION_ICON_UNSPECIFIED",
		1: "TRAY_NOTIFICATION_ICON_INFO",
		2: "TRAY_NOTIFICATION_ICON_WARNING",
		3: "TRAY_NOTIFICATION_ICON_ERROR",
	}
	TrayNotificationIcon_value = map[string]int32{
		"TRAY_NOTIFICATION_ICON_UNSPECIFIED": 0,
		"TRAY_NOTIFICATION_ICON_INFO":        1,
		"TRAY_NOTIFICATION_ICON_WARNING":     2,
		"TRAY_NOTIFICATION_ICON_ERROR":       3,
	}
)

func (x TrayNotificationIcon) Enum() *TrayNotificationIcon {
	p := new(TrayNotificationIcon)
	*p = x
	return p
}

func (x TrayNotificationIcon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrayNotificationIcon) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_moqi_proto_enumTypes[2].Descriptor()
}

func (TrayNotificationIcon) Type() protoreflect.EnumType {
	return &file_proto_moqi_proto_enumTypes[2]
}

func (x TrayNotificationIcon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrayNotificationIcon.Descriptor instead.
func (TrayNotificationIcon) EnumDescriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{2}
}

type KeyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharCode      uint32                 `protobuf:"varint,1,opt,name=char_code,json=charCode,proto3" json:"char_code,omitempty"`
	KeyCode       uint32                 `protobuf:"varint,2,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"`
	RepeatCount   uint32                 `protobuf:"varint,3,opt,name=repeat_count,json=repeatCount,proto3" json:"repeat_count,omitempty"`
	ScanCode      uint32                 `protobuf:"varint,4,opt,name=scan_code,json=scanCode,proto3" json:"scan_code,omitempty"`
	IsExtended    bool                   `protobuf:"varint,5,opt,name=is_extended,json=isExtended,proto3" json:"is_extended,omitempty"`
	KeyStates     []uint32               `protobuf:"varint,6,rep,packed,name=key_states,json=keyStates,proto3" json:"key_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEvent) Reset() {
	*x = KeyEvent{}
	mi := &file_proto_moqi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEvent) ProtoMessage() {}

func (x *KeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEvent.ProtoReflect.Descriptor instead.
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{0}
}

func (x *KeyEvent) GetCharCode() uint32 {
	if x != nil {
		return x.CharCode
	}
	return 0
}

func (x *KeyEvent) GetKeyCode() uint32 {
	if x != nil {
		return x.KeyCode
	}
	return 0
}

func (x *KeyEvent) GetRepeatCount() uint32 {
	if x != nil {
		return x.RepeatCount
	}
	return 0
}

func (x *KeyEvent) GetScanCode() uint32 {
	if x != nil {
		return x.ScanCode
	}
	return 0
}

func (x *KeyEvent) GetIsExtended() bool {
	if x != nil {
		return x.IsExtended
	}
	return false
}

func (x *KeyEvent) GetKeyStates() []uint32 {
	if x != nil {
		return x.KeyStates
	}
	return nil
}

type ButtonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Tooltip       string                 `protobuf:"bytes,4,opt,name=tooltip,proto3" json:"tooltip,omitempty"`
	CommandId     uint32                 `protobuf:"varint,5,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          ButtonType             `protobuf:"varint,6,opt,name=type,proto3,enum=moqi.protocol.ButtonType" json:"type,omitempty"`
	Enable        bool                   `protobuf:"varint,7,opt,name=enable,proto3" json:"enable,omitempty"`
	Toggled       bool                   `protobuf:"varint,8,opt,name=toggled,proto3" json:"toggled,omitempty"`
	Style         *uint32                `protobuf:"varint,9,opt,name=style,proto3,oneof" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonInfo) Reset() {
	*x = ButtonInfo{}
	mi := &file_proto_moqi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonInfo) ProtoMessage() {}

func (x *ButtonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonInfo.ProtoReflect.Descriptor instead.
func (*ButtonInfo) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{1}
}

func (x *ButtonInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ButtonInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ButtonInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ButtonInfo) GetTooltip() string {
	if x != nil {
		return x.Tooltip
	}
	return ""
}

func (x *ButtonInfo) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *ButtonInfo) GetType() ButtonType {
	if x != nil {
		return x.Type
	}
	return ButtonType_BUTTON_TYPE_UNSPECIFIED
}

func (x *ButtonInfo) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ButtonInfo) GetToggled() bool {
	if x != nil {
		return x.Toggled
	}
	return false
}

func (x *ButtonInfo) GetStyle() uint32 {
	if x != nil && x.Style != nil {
		return *x.Style
	}
	return 0
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Checked       bool                   `protobuf:"varint,3,opt,name=checked,proto3" json:"checked,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Submenu       []*MenuItem            `protobuf:"bytes,5,rep,name=submenu,proto3" json:"submenu,omitempty"`
	Separator     bool                   `protobuf:"varint,6,opt,name=separator,proto3" json:"separator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_proto_moqi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{2}
}

func (x *MenuItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MenuItem) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

func (x *MenuItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MenuItem) GetSubmenu() []*MenuItem {
	if x != nil {
		return x.Submenu
	}
	return nil
}

func (x *MenuItem) GetSeparator() bool {
	if x != nil {
		return x.Separator
	}
	return false
}

type PreservedKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyCode       uint32                 `protobuf:"varint,1,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"`
	Modifiers     uint32                 `protobuf:"varint,2,opt,name=modifiers,proto3" json:"modifiers,omitempty"`
	Guid          string                 `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreservedKey) Reset() {
	*x = PreservedKey{}
	mi := &file_proto_moqi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreservedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreservedKey) ProtoMessage() {}

func (x *PreservedKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreservedKey.ProtoReflect.Descriptor instead.
func (*PreservedKey) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{3}
}

func (x *PreservedKey) GetKeyCode() uint32 {
	if x != nil {
		return x.KeyCode
	}
	return 0
}

func (x *PreservedKey) GetModifiers() uint32 {
	if x != nil {
		return x.Modifiers
	}
	return 0
}

func (x *PreservedKey) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type CandidateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateEntry) Reset() {
	*x = CandidateEntry{}
	mi := &file_proto_moqi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateEntry) ProtoMessage() {}

func (x *CandidateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateEntry.ProtoReflect.Descriptor instead.
func (*CandidateEntry) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{4}
}

func (x *CandidateEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CandidateEntry) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CustomizeUi struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CandFontName              *string                `protobuf:"bytes,1,opt,name=cand_font_name,json=candFontName,proto3,oneof" json:"cand_font_name,omitempty"`
	CandFontSize              *uint32                `protobuf:"varint,2,opt,name=cand_font_size,json=candFontSize,proto3,oneof" json:"cand_font_size,omitempty"`
	CandPerRow                *uint32                `protobuf:"varint,3,opt,name=cand_per_row,json=candPerRow,proto3,oneof" json:"cand_per_row,omitempty"`
	CandUseCursor             *bool                  `protobuf:"varint,4,opt,name=cand_use_cursor,json=candUseCursor,proto3,oneof" json:"cand_use_cursor,omitempty"`
	InlinePreedit             *bool                  `protobuf:"varint,5,opt,name=inline_preedit,json=inlinePreedit,proto3,oneof" json:"inline_preedit,omitempty"`
	CandBackgroundColor       *string                `protobuf:"bytes,6,opt,name=cand_background_color,json=candBackgroundColor,proto3,oneof" json:"cand_background_color,omitempty"`
	CandHighlightColor        *string                `protobuf:"bytes,7,opt,name=cand_highlight_color,json=candHighlightColor,proto3,oneof" json:"cand_highlight_color,omitempty"`
	CandTextColor             *string                `protobuf:"bytes,8,opt,name=cand_text_color,json=candTextColor,proto3,oneof" json:"cand_text_color,omitempty"`
	CandHighlightTextColor    *string                `protobuf:"bytes,9,opt,name=cand_highlight_text_color,json=candHighlightTextColor,proto3,oneof" json:"cand_highlight_text_color,omitempty"`
	CandCommentFontSize       *uint32                `protobuf:"varint,10,opt,name=cand_comment_font_size,json=candCommentFontSize,proto3,oneof" json:"cand_comment_font_size,omitempty"`
	AutoPairQuotes            *bool                  `protobuf:"varint,11,opt,name=auto_pair_quotes,json=autoPairQuotes,proto3,oneof" json:"auto_pair_quotes,omitempty"`
	SemicolonSelectSecond     *bool                  `protobuf:"varint,12,opt,name=semicolon_select_second,json=semicolonSelectSecond,proto3,oneof" json:"semicolon_select_second,omitempty"`
	CandCommentFontName       *string                `protobuf:"bytes,13,opt,name=cand_comment_font_name,json=candCommentFontName,proto3,oneof" json:"cand_comment_font_name,omitempty"`
	CandCommentColor          *string                `protobuf:"bytes,14,opt,name=cand_comment_color,json=candCommentColor,proto3,oneof" json:"cand_comment_color,omitempty"`
	CandCommentHighlightColor *string                `protobuf:"bytes,15,opt,name=cand_comment_highlight_color,json=candCommentHighlightColor,proto3,oneof" json:"cand_comment_highlight_color,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CustomizeUi) Reset() {
	*x = CustomizeUi{}
	mi := &file_proto_moqi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomizeUi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomizeUi) ProtoMessage() {}

func (x *CustomizeUi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomizeUi.ProtoReflect.Descriptor instead.
func (*CustomizeUi) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{5}
}

func (x *CustomizeUi) GetCandFontName() string {
	if x != nil && x.CandFontName != nil {
		return *x.CandFontName
	}
	return ""
}

func (x *CustomizeUi) GetCandFontSize() uint32 {
	if x != nil && x.CandFontSize != nil {
		return *x.CandFontSize
	}
	return 0
}

func (x *CustomizeUi) GetCandPerRow() uint32 {
	if x != nil && x.CandPerRow != nil {
		return *x.CandPerRow
	}
	return 0
}

func (x *CustomizeUi) GetCandUseCursor() bool {
	if x != nil && x.CandUseCursor != nil {
		return *x.CandUseCursor
	}
	return false
}

func (x *CustomizeUi) GetInlinePreedit() bool {
	if x != nil && x.InlinePreedit != nil {
		return *x.InlinePreedit
	}
	return false
}

func (x *CustomizeUi) GetCandBackgroundColor() string {
	if x != nil && x.CandBackgroundColor != nil {
		return *x.CandBackgroundColor
	}
	return ""
}

func (x *CustomizeUi) GetCandHighlightColor() string {
	if x != nil && x.CandHighlightColor != nil {
		return *x.CandHighlightColor
	}
	return ""
}

func (x *CustomizeUi) GetCandTextColor() string {
	if x != nil && x.CandTextColor != nil {
		return *x.CandTextColor
	}
	return ""
}

func (x *CustomizeUi) GetCandHighlightTextColor() string {
	if x != nil && x.CandHighlightTextColor != nil {
		return *x.CandHighlightTextColor
	}
	return ""
}

func (x *CustomizeUi) GetCandCommentFontSize() uint32 {
	if x != nil && x.CandCommentFontSize != nil {
		return *x.CandCommentFontSize
	}
	return 0
}

func (x *CustomizeUi) GetAutoPairQuotes() bool {
	if x != nil && x.AutoPairQuotes != nil {
		return *x.AutoPairQuotes
	}
	return false
}

func (x *CustomizeUi) GetSemicolonSelectSecond() bool {
	if x != nil && x.SemicolonSelectSecond != nil {
		return *x.SemicolonSelectSecond
	}
	return false
}

func (x *CustomizeUi) GetCandCommentFontName() string {
	if x != nil && x.CandCommentFontName != nil {
		return *x.CandCommentFontName
	}
	return ""
}

func (x *CustomizeUi) GetCandCommentColor() string {
	if x != nil && x.CandCommentColor != nil {
		return *x.CandCommentColor
	}
	return ""
}

func (x *CustomizeUi) GetCandCommentHighlightColor() string {
	if x != nil && x.CandCommentHighlightColor != nil {
		return *x.CandCommentHighlightColor
	}
	return ""
}

type MessageWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWindow) Reset() {
	*x = MessageWindow{}
	mi := &file_proto_moqi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWindow) ProtoMessage() {}

func (x *MessageWindow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWindow.ProtoReflect.Descriptor instead.
func (*MessageWindow) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{6}
}

func (x *MessageWindow) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageWindow) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type TrayNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Icon          TrayNotificationIcon   `protobuf:"varint,3,opt,name=icon,proto3,enum=moqi.protocol.TrayNotificationIcon" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrayNotification) Reset() {
	*x = TrayNotification{}
	mi := &file_proto_moqi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrayNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrayNotification) ProtoMessage() {}

func (x *TrayNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrayNotification.ProtoReflect.Descriptor instead.
func (*TrayNotification) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{7}
}

func (x *TrayNotification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrayNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TrayNotification) GetIcon() TrayNotificationIcon {
	if x != nil {
		return x.Icon
	}
	return TrayNotificationIcon_TRAY_NOTIFICATION_ICON_UNSPECIFIED
}

type ClientRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SeqNum            uint32                 `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Method            Method                 `protobuf:"varint,2,opt,name=method,proto3,enum=moqi.protocol.Method" json:"method,omitempty"`
	Guid              *string                `protobuf:"bytes,3,opt,name=guid,proto3,oneof" json:"guid,omitempty"`
	IsWindows8Above   bool                   `protobuf:"varint,4,opt,name=is_windows8_above,json=isWindows8Above,proto3" json:"is_windows8_above,omitempty"`
	IsMetroApp        bool                   `protobuf:"varint,5,opt,name=is_metro_app,json=isMetroApp,proto3" json:"is_metro_app,omitempty"`
	IsUiLess          bool                   `protobuf:"varint,6,opt,name=is_ui_less,json=isUiLess,proto3" json:"is_ui_less,omitempty"`
	IsConsole         bool                   `protobuf:"varint,7,opt,name=is_console,json=isConsole,proto3" json:"is_console,omitempty"`
	Opened            bool                   `protobuf:"varint,8,opt,name=opened,proto3" json:"opened,omitempty"`
	Forced            bool                   `protobuf:"varint,9,opt,name=forced,proto3" json:"forced,omitempty"`
	CommandType       uint32                 `protobuf:"varint,10,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	KeyEvent          *KeyEvent              `protobuf:"bytes,11,opt,name=key_event,json=keyEvent,proto3" json:"key_event,omitempty"`
	CompositionString string                 `protobuf:"bytes,12,opt,name=composition_string,json=compositionString,proto3" json:"composition_string,omitempty"`
	CandidateList     []string               `protobuf:"bytes,13,rep,name=candidate_list,json=candidateList,proto3" json:"candidate_list,omitempty"`
	ShowCandidates    bool                   `protobuf:"varint,14,opt,name=show_candidates,json=showCandidates,proto3" json:"show_candidates,omitempty"`
	CursorPos         int32                  `protobuf:"varint,15,opt,name=cursor_pos,json=cursorPos,proto3" json:"cursor_pos,omitempty"`
	SelStart          int32                  `protobuf:"varint,16,opt,name=sel_start,json=selStart,proto3" json:"sel_start,omitempty"`
	SelEnd            int32                  `protobuf:"varint,17,opt,name=sel_end,json=selEnd,proto3" json:"sel_end,omitempty"`
	ButtonId          *string                `protobuf:"bytes,18,opt,name=button_id,json=buttonId,proto3,oneof" json:"button_id,omitempty"`
	CommandId         *uint32                `protobuf:"varint,19,opt,name=command_id,json=commandId,proto3,oneof" json:"command_id,omitempty"`
	PreservedKeyGuid  *string                `protobuf:"bytes,20,opt,name=preserved_key_guid,json=preservedKeyGuid,proto3,oneof" json:"preserved_key_guid,omitempty"`
	CompartmentGuid   *string                `protobuf:"bytes,21,opt,name=compartment_guid,json=compartmentGuid,proto3,oneof" json:"compartment_guid,omitempty"`
	IsKeyboardOpen    bool                   `protobuf:"varint,22,opt,name=is_keyboard_open,json=isKeyboardOpen,proto3" json:"is_keyboard_open,omitempty"`
	ClientId          *string                `protobuf:"bytes,23,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_proto_moqi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{8}
}

func (x *ClientRequest) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *ClientRequest) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_METHOD_UNSPECIFIED
}

func (x *ClientRequest) GetGuid() string {
	if x != nil && x.Guid != nil {
		return *x.Guid
	}
	return ""
}

func (x *ClientRequest) GetIsWindows8Above() bool {
	if x != nil {
		return x.IsWindows8Above
	}
	return false
}

func (x *ClientRequest) GetIsMetroApp() bool {
	if x != nil {
		return x.IsMetroApp
	}
	return false
}

func (x *ClientRequest) GetIsUiLess() bool {
	if x != nil {
		return x.IsUiLess
	}
	return false
}

func (x *ClientRequest) GetIsConsole() bool {
	if x != nil {
		return x.IsConsole
	}
	return false
}

func (x *ClientRequest) GetOpened() bool {
	if x != nil {
		return x.Opened
	}
	return false
}

func (x *ClientRequest) GetForced() bool {
	if x != nil {
		return x.Forced
	}
	return false
}

func (x *ClientRequest) GetCommandType() uint32 {
	if x != nil {
		return x.CommandType
	}
	return 0
}

func (x *ClientRequest) GetKeyEvent() *KeyEvent {
	if x != nil {
		return x.KeyEvent
	}
	return nil
}

func (x *ClientRequest) GetCompositionString() string {
	if x != nil {
		return x.CompositionString
	}
	return ""
}

func (x *ClientRequest) GetCandidateList() []string {
	if x != nil {
		return x.CandidateList
	}
	return nil
}

func (x *ClientRequest) GetShowCandidates() bool {
	if x != nil {
		return x.ShowCandidates
	}
	return false
}

func (x *ClientRequest) GetCursorPos() int32 {
	if x != nil {
		return x.CursorPos
	}
	return 0
}

func (x *ClientRequest) GetSelStart() int32 {
	if x != nil {
		return x.SelStart
	}
	return 0
}

func (x *ClientRequest) GetSelEnd() int32 {
	if x != nil {
		return x.SelEnd
	}
	return 0
}

func (x *ClientRequest) GetButtonId() string {
	if x != nil && x.ButtonId != nil {
		return *x.ButtonId
	}
	return ""
}

func (x *ClientRequest) GetCommandId() uint32 {
	if x != nil && x.CommandId != nil {
		return *x.CommandId
	}
	return 0
}

func (x *ClientRequest) GetPreservedKeyGuid() string {
	if x != nil && x.PreservedKeyGuid != nil {
		return *x.PreservedKeyGuid
	}
	return ""
}

func (x *ClientRequest) GetCompartmentGuid() string {
	if x != nil && x.CompartmentGuid != nil {
		return *x.CompartmentGuid
	}
	return ""
}

func (x *ClientRequest) GetIsKeyboardOpen() bool {
	if x != nil {
		return x.IsKeyboardOpen
	}
	return false
}

func (x *ClientRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type ServerResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientId           *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	SeqNum             uint32                 `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Success            bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ReturnValue        int32                  `protobuf:"varint,4,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	MenuItems          []*MenuItem            `protobuf:"bytes,5,rep,name=menu_items,json=menuItems,proto3" json:"menu_items,omitempty"`
	CompositionString  string                 `protobuf:"bytes,6,opt,name=composition_string,json=compositionString,proto3" json:"composition_string,omitempty"`
	CommitString       string                 `protobuf:"bytes,7,opt,name=commit_string,json=commitString,proto3" json:"commit_string,omitempty"`
	CandidateList      []string               `protobuf:"bytes,8,rep,name=candidate_list,json=candidateList,proto3" json:"candidate_list,omitempty"`
	ShowCandidates     bool                   `protobuf:"varint,9,opt,name=show_candidates,json=showCandidates,proto3" json:"show_candidates,omitempty"`
	CursorPos          int32                  `protobuf:"varint,10,opt,name=cursor_pos,json=cursorPos,proto3" json:"cursor_pos,omitempty"`
	CompositionCursor  int32                  `protobuf:"varint,11,opt,name=composition_cursor,json=compositionCursor,proto3" json:"composition_cursor,omitempty"`
	CandidateCursor    int32                  `protobuf:"varint,12,opt,name=candidate_cursor,json=candidateCursor,proto3" json:"candidate_cursor,omitempty"`
	SelStart           int32                  `protobuf:"varint,13,opt,name=sel_start,json=selStart,proto3" json:"sel_start,omitempty"`
	SelEnd             int32                  `protobuf:"varint,14,opt,name=sel_end,json=selEnd,proto3" json:"sel_end,omitempty"`
	SetSelKeys         string                 `protobuf:"bytes,15,opt,name=set_sel_keys,json=setSelKeys,proto3" json:"set_sel_keys,omitempty"`
	CustomizeUi        *CustomizeUi           `protobuf:"bytes,16,opt,name=customize_ui,json=customizeUi,proto3,oneof" json:"customize_ui,omitempty"`
	AddButton          []*ButtonInfo          `protobuf:"bytes,17,rep,name=add_button,json=addButton,proto3" json:"add_button,omitempty"`
	RemoveButton       []string               `protobuf:"bytes,18,rep,name=remove_button,json=removeButton,proto3" json:"remove_button,omitempty"`
	ChangeButton       []*ButtonInfo          `protobuf:"bytes,19,rep,name=change_button,json=changeButton,proto3" json:"change_button,omitempty"`
	ShowMessage        *MessageWindow         `protobuf:"bytes,20,opt,name=show_message,json=showMessage,proto3,oneof" json:"show_message,omitempty"`
	HideMessage        bool                   `protobuf:"varint,21,opt,name=hide_message,json=hideMessage,proto3" json:"hide_message,omitempty"`
	OpenKeyboard       bool                   `protobuf:"varint,22,opt,name=open_keyboard,json=openKeyboard,proto3" json:"open_keyboard,omitempty"`
	AddPreservedKey    []*PreservedKey        `protobuf:"bytes,23,rep,name=add_preserved_key,json=addPreservedKey,proto3" json:"add_preserved_key,omitempty"`
	RemovePreservedKey []string               `protobuf:"bytes,24,rep,name=remove_preserved_key,json=removePreservedKey,proto3" json:"remove_preserved_key,omitempty"`
	Error              string                 `protobuf:"bytes,25,opt,name=error,proto3" json:"error,omitempty"`
	TrayNotification   *TrayNotification      `protobuf:"bytes,26,opt,name=tray_notification,json=trayNotification,proto3,oneof" json:"tray_notification,omitempty"`
	CandidateEntries   []*CandidateEntry      `protobuf:"bytes,27,rep,name=candidate_entries,json=candidateEntries,proto3" json:"candidate_entries,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_proto_moqi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_moqi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_moqi_proto_rawDescGZIP(), []int{9}
}

func (x *ServerResponse) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *ServerResponse) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *ServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerResponse) GetReturnValue() int32 {
	if x != nil {
		return x.ReturnValue
	}
	return 0
}

func (x *ServerResponse) GetMenuItems() []*MenuItem {
	if x != nil {
		return x.MenuItems
	}
	return nil
}

func (x *ServerResponse) GetCompositionString() string {
	if x != nil {
		return x.CompositionString
	}
	return ""
}

func (x *ServerResponse) GetCommitString() string {
	if x != nil {
		return x.CommitString
	}
	return ""
}

func (x *ServerResponse) GetCandidateList() []string {
	if x != nil {
		return x.CandidateList
	}
	return nil
}

func (x *ServerResponse) GetShowCandidates() bool {
	if x != nil {
		return x.ShowCandidates
	}
	return false
}

func (x *ServerResponse) GetCursorPos() int32 {
	if x != nil {
		return x.CursorPos
	}
	return 0
}

func (x *ServerResponse) GetCompositionCursor() int32 {
	if x != nil {
		return x.CompositionCursor
	}
	return 0
}

func (x *ServerResponse) GetCandidateCursor() int32 {
	if x != nil {
		return x.CandidateCursor
	}
	return 0
}

func (x *ServerResponse) GetSelStart() int32 {
	if x != nil {
		return x.SelStart
	}
	return 0
}

func (x *ServerResponse) GetSelEnd() int32 {
	if x != nil {
		return x.SelEnd
	}
	return 0
}

func (x *ServerResponse) GetSetSelKeys() string {
	if x != nil {
		return x.SetSelKeys
	}
	return ""
}

func (x *ServerResponse) GetCustomizeUi() *CustomizeUi {
	if x != nil {
		return x.CustomizeUi
	}
	return nil
}

func (x *ServerResponse) GetAddButton() []*ButtonInfo {
	if x != nil {
		return x.AddButton
	}
	return nil
}

func (x *ServerResponse) GetRemoveButton() []string {
	if x != nil {
		return x.RemoveButton
	}
	return nil
}

func (x *ServerResponse) GetChangeButton() []*ButtonInfo {
	if x != nil {
		return x.ChangeButton
	}
	return nil
}

func (x *ServerResponse) GetShowMessage() *MessageWindow {
	if x != nil {
		return x.ShowMessage
	}
	return nil
}

func (x *ServerResponse) GetHideMessage() bool {
	if x != nil {
		return x.HideMessage
	}
	return false
}

func (x *ServerResponse) GetOpenKeyboard() bool {
	if x != nil {
		return x.OpenKeyboard
	}
	return false
}

func (x *ServerResponse) GetAddPreservedKey() []*PreservedKey {
	if x != nil {
		return x.AddPreservedKey
	}
	return nil
}

func (x *ServerResponse) GetRemovePreservedKey() []string {
	if x != nil {
		return x.RemovePreservedKey
	}
	return nil
}

func (x *ServerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServerResponse) GetTrayNotification() *TrayNotification {
	if x != nil {
		return x.TrayNotification
	}
	return nil
}

func (x *ServerResponse) GetCandidateEntries() []*CandidateEntry {
	if x != nil {
		return x.CandidateEntries
	}
	return nil
}

var File_proto_moqi_proto protoreflect.FileDescriptor

const file_proto_moqi_proto_rawDesc = "" +
	"\n" +
	"\x10proto/moqi.proto\x12\rmoqi.protocol\"\xc2\x01\n" +
	"\bKeyEvent\x12\x1b\n" +
	"\tchar_code\x18\x01 \x01(\rR\bcharCode\x12\x19\n" +
	"\bkey_code\x18\x02 \x01(\rR\akeyCode\x12!\n" +
	"\frepeat_count\x18\x03 \x01(\rR\vrepeatCount\x12\x1b\n" +
	"\tscan_code\x18\x04 \x01(\rR\bscanCode\x12\x1f\n" +
	"\vis_extended\x18\x05 \x01(\bR\n" +
	"isExtended\x12\x1d\n" +
	"\n" +
	"key_states\x18\x06 \x03(\rR\tkeyStates\"\x83\x02\n" +
	"\n" +
	"ButtonInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\atooltip\x18\x04 \x01(\tR\atooltip\x12\x1d\n" +
	"\n" +
	"command_id\x18\x05 \x01(\rR\tcommandId\x12-\n" +
	"\x04type\x18\x06 \x01(\x0e2\x19.moqi.protocol.ButtonTypeR\x04type\x12\x16\n" +
	"\x06enable\x18\a \x01(\bR\x06enable\x12\x18\n" +
	"\atoggled\x18\b \x01(\bR\atoggled\x12\x19\n" +
	"\x05style\x18\t \x01(\rH\x00R\x05style\x88\x01\x01B\b\n" +
	"\x06_style\"\xb3\x01\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\achecked\x18\x03 \x01(\bR\achecked\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x121\n" +
	"\asubmenu\x18\x05 \x03(\v2\x17.moqi.protocol.MenuItemR\asubmenu\x12\x1c\n" +
	"\tseparator\x18\x06 \x01(\bR\tseparator\"[\n" +
	"\fPreservedKey\x12\x19\n" +
	"\bkey_code\x18\x01 \x01(\rR\akeyCode\x12\x1c\n" +
	"\tmodifiers\x18\x02 \x01(\rR\tmodifiers\x12\x12\n" +
	"\x04guid\x18\x03 \x01(\tR\x04guid\">\n" +
	"\x0eCandidateEntry\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"\xfb\b\n" +
	"\vCustomizeUi\x12)\n" +
	"\x0ecand_font_name\x18\x01 \x01(\tH\x00R\fcandFontName\x88\x01\x01\x12)\n" +
	"\x0ecand_font_size\x18\x02 \x01(\rH\x01R\fcandFontSize\x88\x01\x01\x12%\n" +
	"\fcand_per_row\x18\x03 \x01(\rH\x02R\n" +
	"candPerRow\x88\x01\x01\x12+\n" +
	"\x0fcand_use_cursor\x18\x04 \x01(\bH\x03R\rcandUseCursor\x88\x01\x01\x12*\n" +
	"\x0einline_preedit\x18\x05 \x01(\bH\x04R\rinlinePreedit\x88\x01\x01\x127\n" +
	"\x15cand_background_color\x18\x06 \x01(\tH\x05R\x13candBackgroundColor\x88\x01\x01\x125\n" +
	"\x14cand_highlight_color\x18\a \x01(\tH\x06R\x12candHighlightColor\x88\x01\x01\x12+\n" +
	"\x0fcand_text_color\x18\b \x01(\tH\aR\rcandTextColor\x88\x01\x01\x12>\n" +
	"\x19cand_highlight_text_color\x18\t \x01(\tH\bR\x16candHighlightTextColor\x88\x01\x01\x128\n" +
	"\x16cand_comment_font_size\x18\n" +
	" \x01(\rH\tR\x13candCommentFontSize\x88\x01\x01\x12-\n" +
	"\x10auto_pair_quotes\x18\v \x01(\bH\n" +
	"R\x0eautoPairQuotes\x88\x01\x01\x12;\n" +
	"\x17semicolon_select_second\x18\f \x01(\bH\vR\x15semicolonSelectSecond\x88\x01\x01\x128\n" +
	"\x16cand_comment_font_name\x18\r \x01(\tH\fR\x13candCommentFontName\x88\x01\x01\x121\n" +
	"\x12cand_comment_color\x18\x0e \x01(\tH\rR\x10candCommentColor\x88\x01\x01\x12D\n" +
	"\x1ccand_comment_highlight_color\x18\x0f \x01(\tH\x0eR\x19candCommentHighlightColor\x88\x01\x01B\x11\n" +
	"\x0f_cand_font_nameB\x11\n" +
	"\x0f_cand_font_sizeB\x0f\n" +
	"\r_cand_per_rowB\x12\n" +
	"\x10_cand_use_cursorB\x11\n" +
	"\x0f_inline_preeditB\x18\n" +
	"\x16_cand_background_colorB\x17\n" +
	"\x15_cand_highlight_colorB\x12\n" +
	"\x10_cand_text_colorB\x1c\n" +
	"\x1a_cand_highlight_text_colorB\x19\n" +
	"\x17_cand_comment_font_sizeB\x13\n" +
	"\x11_auto_pair_quotesB\x1a\n" +
	"\x18_semicolon_select_secondB\x19\n" +
	"\x17_cand_comment_font_nameB\x15\n" +
	"\x13_cand_comment_colorB\x1f\n" +
	"\x1d_cand_comment_highlight_color\"E\n" +
	"\rMessageWindow\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\"{\n" +
	"\x10TrayNotification\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04icon\x18\x03 \x01(\x0e2#.moqi.protocol.TrayNotificationIconR\x04icon\"\xad\a\n" +
	"\rClientRequest\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\rR\x06seqNum\x12-\n" +
	"\x06method\x18\x02 \x01(\x0e2\x15.moqi.protocol.MethodR\x06method\x12\x17\n" +
	"\x04guid\x18\x03 \x01(\tH\x00R\x04guid\x88\x01\x01\x12*\n" +
	"\x11is_windows8_above\x18\x04 \x01(\bR\x0fisWindows8Above\x12 \n" +
	"\fis_metro_app\x18\x05 \x01(\bR\n" +
	"isMetroApp\x12\x1c\n" +
	"\n" +
	"is_ui_less\x18\x06 \x01(\bR\bisUiLess\x12\x1d\n" +
	"\n" +
	"is_console\x18\a \x01(\bR\tisConsole\x12\x16\n" +
	"\x06opened\x18\b \x01(\bR\x06opened\x12\x16\n" +
	"\x06forced\x18\t \x01(\bR\x06forced\x12!\n" +
	"\fcommand_type\x18\n" +
	" \x01(\rR\vcommandType\x124\n" +
	"\tkey_event\x18\v \x01(\v2\x17.moqi.protocol.KeyEventR\bkeyEvent\x12-\n" +
	"\x12composition_string\x18\f \x01(\tR\x11compositionString\x12%\n" +
	"\x0ecandidate_list\x18\r \x03(\tR\rcandidateList\x12'\n" +
	"\x0fshow_candidates\x18\x0e \x01(\bR\x0eshowCandidates\x12\x1d\n" +
	"\n" +
	"cursor_pos\x18\x0f \x01(\x05R\tcursorPos\x12\x1b\n" +
	"\tsel_start\x18\x10 \x01(\x05R\bselStart\x12\x17\n" +
	"\asel_end\x18\x11 \x01(\x05R\x06selEnd\x12 \n" +
	"\tbutton_id\x18\x12 \x01(\tH\x01R\bbuttonId\x88\x01\x01\x12\"\n" +
	"\n" +
	"command_id\x18\x13 \x01(\rH\x02R\tcommandId\x88\x01\x01\x121\n" +
	"\x12preserved_key_guid\x18\x14 \x01(\tH\x03R\x10preservedKeyGuid\x88\x01\x01\x12.\n" +
	"\x10compartment_guid\x18\x15 \x01(\tH\x04R\x0fcompartmentGuid\x88\x01\x01\x12(\n" +
	"\x10is_keyboard_open\x18\x16 \x01(\bR\x0eisKeyboardOpen\x12 \n" +
	"\tclient_id\x18\x17 \x01(\tH\x05R\bclientId\x88\x01\x01B\a\n" +
	"\x05_guidB\f\n" +
	"\n" +
	"_button_idB\r\n" +
	"\v_command_idB\x15\n" +
	"\x13_preserved_key_guidB\x13\n" +
	"\x11_compartment_guidB\f\n" +
	"\n" +
	"_client_id\"\x9c\n" +
	"\n" +
	"\x0eServerResponse\x12 \n" +
	"\tclient_id\x18\x01 \x01(\tH\x00R\bclientId\x88\x01\x01\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\rR\x06seqNum\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12!\n" +
	"\freturn_value\x18\x04 \x01(\x05R\vreturnValue\x126\n" +
	"\n" +
	"menu_items\x18\x05 \x03(\v2\x17.moqi.protocol.MenuItemR\tmenuItems\x12-\n" +
	"\x12composition_string\x18\x06 \x01(\tR\x11compositionString\x12#\n" +
	"\rcommit_string\x18\a \x01(\tR\fcommitString\x12%\n" +
	"\x0ecandidate_list\x18\b \x03(\tR\rcandidateList\x12'\n" +
	"\x0fshow_candidates\x18\t \x01(\bR\x0eshowCandidates\x12\x1d\n" +
	"\n" +
	"cursor_pos\x18\n" +
	" \x01(\x05R\tcursorPos\x12-\n" +
	"\x12composition_cursor\x18\v \x01(\x05R\x11compositionCursor\x12)\n" +
	"\x10candidate_cursor\x18\f \x01(\x05R\x0fcandidateCursor\x12\x1b\n" +
	"\tsel_start\x18\r \x01(\x05R\bselStart\x12\x17\n" +
	"\asel_end\x18\x0e \x01(\x05R\x06selEnd\x12 \n" +
	"\fset_sel_keys\x18\x0f \x01(\tR\n" +
	"setSelKeys\x12B\n" +
	"\fcustomize_ui\x18\x10 \x01(\v2\x1a.moqi.protocol.CustomizeUiH\x01R\vcustomizeUi\x88\x01\x01\x128\n" +
	"\n" +
	"add_button\x18\x11 \x03(\v2\x19.moqi.protocol.ButtonInfoR\taddButton\x12#\n" +
	"\rremove_button\x18\x12 \x03(\tR\fremoveButton\x12>\n" +
	"\rchange_button\x18\x13 \x03(\v2\x19.moqi.protocol.ButtonInfoR\fchangeButton\x12D\n" +
	"\fshow_message\x18\x14 \x01(\v2\x1c.moqi.protocol.MessageWindowH\x02R\vshowMessage\x88\x01\x01\x12!\n" +
	"\fhide_message\x18\x15 \x01(\bR\vhideMessage\x12#\n" +
	"\ropen_keyboard\x18\x16 \x01(\bR\fopenKeyboard\x12G\n" +
	"\x11add_preserved_key\x18\x17 \x03(\v2\x1b.moqi.protocol.PreservedKeyR\x0faddPreservedKey\x120\n" +
	"\x14remove_preserved_key\x18\x18 \x03(\tR\x12removePreservedKey\x12\x14\n" +
	"\x05error\x18\x19 \x01(\tR\x05error\x12Q\n" +
	"\x11tray_notification\x18\x1a \x01(\v2\x1f.moqi.protocol.TrayNotificationH\x03R\x10trayNotification\x88\x01\x01\x12J\n" +
	"\x11candidate_entries\x18\x1b \x03(\v2\x1d.moqi.protocol.CandidateEntryR\x10candidateEntriesB\f\n" +
	"\n" +
	"_client_idB\x0f\n" +
	"\r_customize_uiB\x0f\n" +
	"\r_show_messageB\x14\n" +
	"\x12_tray_notification*\xb7\x03\n" +
	"\x06Method\x12\x16\n" +
	"\x12METHOD_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMETHOD_INIT\x10\x01\x12\x10\n" +
	"\fMETHOD_CLOSE\x10\x02\x12\x16\n" +
	"\x12METHOD_ON_ACTIVATE\x10\x03\x12\x18\n" +
	"\x14METHOD_ON_DEACTIVATE\x10\x04\x12\x1a\n" +
	"\x16METHOD_FILTER_KEY_DOWN\x10\x05\x12\x16\n" +
	"\x12METHOD_ON_KEY_DOWN\x10\x06\x12\x18\n" +
	"\x14METHOD_FILTER_KEY_UP\x10\a\x12\x14\n" +
	"\x10METHOD_ON_KEY_UP\x10\b\x12\x1b\n" +
	"\x17METHOD_ON_PRESERVED_KEY\x10\t\x12\x15\n" +
	"\x11METHOD_ON_COMMAND\x10\n" +
	"\x12\x12\n" +
	"\x0eMETHOD_ON_MENU\x10\v\x12!\n" +
	"\x1dMETHOD_ON_COMPARTMENT_CHANGED\x10\f\x12%\n" +
	"!METHOD_ON_KEYBOARD_STATUS_CHANGED\x10\r\x12$\n" +
	" METHOD_ON_COMPOSITION_TERMINATED\x10\x0e\x12$\n" +
	" METHOD_ON_LANG_PROFILE_ACTIVATED\x10\x0f*o\n" +
	"\n" +
	"ButtonType\x12\x1b\n" +
	"\x17BUTTON_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BUTTON_TYPE_BUTTON\x10\x01\x12\x16\n" +
	"\x12BUTTON_TYPE_TOGGLE\x10\x02\x12\x14\n" +
	"\x10BUTTON_TYPE_MENU\x10\x03*\xa5\x01\n" +
	"\x14TrayNotificationIcon\x12&\n" +
	"\"TRAY_NOTIFICATION_ICON_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRAY_NOTIFICATION_ICON_INFO\x10\x01\x12\"\n" +
	"\x1eTRAY_NOTIFICATION_ICON_WARNING\x10\x02\x12 \n" +
	"\x1cTRAY_NOTIFICATION_ICON_ERROR\x10\x03B+Z)github.com/gaboolic/moqi-ime/proto;moqipbb\x06proto3"

var (
	file_proto_moqi_proto_rawDescOnce sync.Once
	file_proto_moqi_proto_rawDescData []byte
)

func file_proto_moqi_proto_rawDescGZIP() []byte {
	file_proto_moqi_proto_rawDescOnce.Do(func() {
		file_proto_moqi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_moqi_proto_rawDesc), len(file_proto_moqi_proto_rawDesc)))
	})
	return file_proto_moqi_proto_rawDescData
}

var file_proto_moqi_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_moqi_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_moqi_proto_goTypes = []any{
	(Method)(0),               // 0: moqi.protocol.Method
	(ButtonType)(0),           // 1: moqi.protocol.ButtonType
	(TrayNotificationIcon)(0), // 2: moqi.protocol.TrayNotificationIcon
	(*KeyEvent)(nil),          // 3: moqi.protocol.KeyEvent
	(*ButtonInfo)(nil),        // 4: moqi.protocol.ButtonInfo
	(*MenuItem)(nil),          // 5: moqi.protocol.MenuItem
	(*PreservedKey)(nil),      // 6: moqi.protocol.PreservedKey
	(*CandidateEntry)(nil),    // 7: moqi.protocol.CandidateEntry
	(*CustomizeUi)(nil),       // 8: moqi.protocol.CustomizeUi
	(*MessageWindow)(nil),     // 9: moqi.protocol.MessageWindow
	(*TrayNotification)(nil),  // 10: moqi.protocol.TrayNotification
	(*ClientRequest)(nil),     // 11: moqi.protocol.ClientRequest
	(*ServerResponse)(nil),    // 12: moqi.protocol.ServerResponse
}
var file_proto_moqi_proto_depIdxs = []int32{
	1,  // 0: moqi.protocol.ButtonInfo.type:type_name -> moqi.protocol.ButtonType
	5,  // 1: moqi.protocol.MenuItem.submenu:type_name -> moqi.protocol.MenuItem
	2,  // 2: moqi.protocol.TrayNotification.icon:type_name -> moqi.protocol.TrayNotificationIcon
	0,  // 3: moqi.protocol.ClientRequest.method:type_name -> moqi.protocol.Method
	3,  // 4: moqi.protocol.ClientRequest.key_event:type_name -> moqi.protocol.KeyEvent
	5,  // 5: moqi.protocol.ServerResponse.menu_items:type_name -> moqi.protocol.MenuItem
	8,  // 6: moqi.protocol.ServerResponse.customize_ui:type_name -> moqi.protocol.CustomizeUi
	4,  // 7: moqi.protocol.ServerResponse.add_button:type_name -> moqi.protocol.ButtonInfo
	4,  // 8: moqi.protocol.ServerResponse.change_button:type_name -> moqi.protocol.ButtonInfo
	9,  // 9: moqi.protocol.ServerResponse.show_message:type_name -> moqi.protocol.MessageWindow
	6,  // 10: moqi.protocol.ServerResponse.add_preserved_key:type_name -> moqi.protocol.PreservedKey
	10, // 11: moqi.protocol.ServerResponse.tray_notification:type_name -> moqi.protocol.TrayNotification
	7,  // 12: moqi.protocol.ServerResponse.candidate_entries:type_name -> moqi.protocol.CandidateEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_moqi_proto_init() }
func file_proto_moqi_proto_init() {
	if File_proto_moqi_proto != nil {
		return
	}
	file_proto_moqi_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_moqi_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_moqi_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_moqi_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_moqi_proto_rawDesc), len(file_proto_moqi_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_moqi_proto_goTypes,
		DependencyIndexes: file_proto_moqi_proto_depIdxs,
		EnumInfos:         file_proto_moqi_proto_enumTypes,
		MessageInfos:      file_proto_moqi_proto_msgTypes,
	}.Build()
	File_proto_moqi_proto = out.File
	file_proto_moqi_proto_goTypes = nil
	file_proto_moqi_proto_depIdxs = nil
}
